name: Docker Image web service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Calculation Docker image
      run: docker build -t print_web_service:$(date +%s) 07_13_docker_distribution/print_web_service/
